name: CI do Estoque
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Preparar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Instalar Dependências
      run: npm install
    - name: Rodar Linting
      run: npm run lint
    - name: Rodar Testes
      run: npm test